### ISSUE TITLE
DatabaseConverter cannot open database files from Sonic the Fighters (2012, PS3)

### ISSUE THREAD

**Issue by coatlessali** [blueskythlikesclouds/MikuMikuLibrary#58]
Apologies if this is outside of the scope of the project, but it seems Sonic the Fighters uses the same (or similar) FARC and Database formats as the Project DIVA games.

Trying to open any database file (AET, Sprite, etc) results in an error on Windows 10:

```
Unhandled Exception: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at MikuMikuLibrary.Databases.AetDatabase.<>c__DisplayClass5_0.<Read>b__0()
   at MikuMikuLibrary.IO.Common.EndianBinaryReader.ReadAtOffset(Int64 offset, Action action)
   at MikuMikuLibrary.Databases.AetDatabase.Read(EndianBinaryReader reader, ISection section)
   at MikuMikuLibrary.IO.BinaryFile.<Load>g__ReadClassic|14_1(<>c__DisplayClass14_0& )
   at MikuMikuLibrary.IO.BinaryFile.Load(Stream source, Boolean leaveOpen)
   at DatabaseConverter.Program.Main(String[] args)
   ```

I have tried running the executable manually from Powershell to no avail.

**Comment by blueskythlikesclouds** [comment]
No, just the file naming is similar. The formats are very different.

**Comment by coatlessali** [comment]
Ah, it would seem so. Sorry for the assumption, and thanks for the quick reply.

I did find it works on `string_array.bin`, which is neat.
